# Generated by Django 5.1.5 on 2025-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_paragraph_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='content',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='ontent',
            field=models.JSONField(default=list),
        ),
    ]
