# Generated by Django 5.1.5 on 2025-01-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_paragraph_content_paragraph_ontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='ontent',
            new_name='content',
        ),
    ]
