# Generated by Django 5.1.5 on 2025-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
